### ISSUE TITLE
Font size change does not take effect until terminal window is resized

### ISSUE THREAD

**Issue by arkady** [trybick/vscode-terminal-zoom#3]
Changing the font size (whether through status bar or Command Pallete) does not take effect until and unless I resize the terminal window/pane -- then the font assumes the selected size.  Tested on following versions:

Version: 1.57.1 (user setup)
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:07.755Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Version: 1.58.0-insider (user setup)
Commit: 6afedfdad59d1f1ba4b614341d21c67775e158a9
Date: 2021-06-21T05:15:13.618Z
Electron: 12.0.11
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by trybick** [comment]
Thanks for reporting this. I am seeing this too. I won't have time to dig into it for another month (I'm on paternity leave). 

But from quickly looking, terminal zoom **is** changing the font size in the vscode settings.json, so maybe we need another command to refresh the terminal? It looks like VSCode has been making updates to various terminal things recently (see VSCode patch notes) so maybe something changed there too.

**Comment by arkady** [comment]
Actually, it looks like this is a (now fixed) bug in VSCode.  See here: https://github.com/microsoft/vscode/issues/127069
