### ISSUE TITLE
Publish to openvsx

### ISSUE THREAD

**Issue by rochacbruno** [trybick/vscode-terminal-zoom#4]
Hi,

I am using https://open-vsx.org/ to install extensions

can this very useful extension be published there?

Thanks

**Comment by trybick** [comment]
Hi @rochacbruno thanks for the message. How do I publish it there? What is the advantage of publishing there?

**Comment by o-l-a-v** [comment]
How to publish:

* https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

Why? The ability to use the extension with VSCodium with its built in marketplace. At least that's what I'd use it for.

* https://github.com/VSCodium/vscodium
* https://vscodium.com/

**Comment by rochacbruno** [comment]
I use https://gitpod.io  (an online IDE running codium server) and there we can install only open-vsx extensions.

**Comment by trybick** [comment]
Thanks for the info guys, this extension is now published on Open VSX
https://open-vsx.org/extension/trybick/terminal-zoom
